export interface UniversitySeed {
  name: string;
  shortName: string;
  city: string;
  province: string; // "Punjab" | "Sindh" | "KPK" | "Balochistan" | "Federal" | "AJK" | "Gilgit-Baltistan"
  type: "public" | "private";
  nationalRank: number | null;
  globalRank: number | null;
  matricWeight: number;
  interWeight: number;
  testWeight: number;
  testName: string;
  testMaxScore: number;
  website: string;
  feesRange: string;
  programs: ProgramSeed[];
}

export interface CutoffHistory {
  year: number;
  cutoff: number;
}

export interface ProgramSeed {
  name: string;
  cutoffTypical: number | null; // Fallback for MVP
  cutoffHistory?: CutoffHistory[]; // Year-wise data for scalability
  eligibility: string;
  seats: number | null;
}

export const UNIVERSITY_SEED_DATA: UniversitySeed[] = [
  // --- FEDERAL / ISLAMABAD ---
  {
    name: "National University of Sciences & Technology",
    shortName: "NUST",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 1,
    globalRank: 650,
    matricWeight: 10,
    interWeight: 15,
    testWeight: 75,
    testName: "NET",
    testMaxScore: 200,
    website: "https://nust.edu.pk",
    feesRange: "PKR 200,000 - 350,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 85, eligibility: "60% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 83, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Artificial Intelligence", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Data Science", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 60 },
      { name: "BS Electrical Engineering", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng", seats: 120 },
      { name: "BS Mechanical Engineering", cutoffTypical: 80, eligibility: "60% FSc Pre-Eng", seats: 100 },
      { name: "BS Civil Engineering", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng", seats: 100 },
      { name: "BS Business Administration", cutoffTypical: 78, eligibility: "60% FSc/FA", seats: 80 },
    ],
  },
  {
    name: "COMSATS University Islamabad",
    shortName: "COMSATS",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 3,
    globalRank: 800,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "NTS NAT",
    testMaxScore: 100,
    website: "https://comsats.edu.pk",
    feesRange: "PKR 120,000 - 220,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 78, eligibility: "50% FSc Pre-Eng/ICS", seats: 250 },
      { name: "BS Software Engineering", cutoffTypical: 76, eligibility: "50% FSc Pre-Eng/ICS", seats: 200 },
      { name: "BS Cyber Security", cutoffTypical: 75, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Electrical Engineering", cutoffTypical: 70, eligibility: "60% FSc Pre-Eng", seats: 150 },
      { name: "BS Business Administration", cutoffTypical: 65, eligibility: "50% FSc/FA", seats: 120 },
    ],
  },
  {
    name: "Pakistan Institute of Engineering and Applied Sciences",
    shortName: "PIEAS",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 4,
    globalRank: 400,
    matricWeight: 15,
    interWeight: 25,
    testWeight: 60,
    testName: "PIEAS Admission Test",
    testMaxScore: 100,
    website: "https://pieas.edu.pk",
    feesRange: "PKR 100,000 - 180,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 60 },
      { name: "BS Electrical Engineering", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng", seats: 60 },
      { name: "BS Mechanical Engineering", cutoffTypical: 83, eligibility: "60% FSc Pre-Eng", seats: 60 },
      { name: "BS Chemical Engineering", cutoffTypical: 80, eligibility: "60% FSc Pre-Eng", seats: 50 },
    ],
  },
  {
    name: "Air University",
    shortName: "Air Uni",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 15,
    globalRank: null,
    matricWeight: 15,
    interWeight: 35,
    testWeight: 50,
    testName: "Air University Entry Test",
    testMaxScore: 100,
    website: "https://au.edu.pk",
    feesRange: "PKR 150,000 - 250,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 74, eligibility: "50% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Cyber Security", cutoffTypical: 73, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Software Engineering", cutoffTypical: 72, eligibility: "50% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Avionics Engineering", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng", seats: 60 },
    ],
  },
  {
    name: "Bahria University",
    shortName: "Bahria",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 20,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "CBT Bahria Test",
    testMaxScore: 100,
    website: "https://bahria.edu.pk",
    feesRange: "PKR 180,000 - 280,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 68, eligibility: "50% FSc Pre-Eng/ICS", seats: 180 },
      { name: "BS Information Technology", cutoffTypical: 65, eligibility: "50% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Business Administration", cutoffTypical: 62, eligibility: "50% FSc/FA", seats: 150 },
    ],
  },

  // --- PUNJAB ---
  {
    name: "Lahore University of Management Sciences",
    shortName: "LUMS",
    city: "Lahore",
    province: "Punjab",
    type: "private",
    nationalRank: 2,
    globalRank: 700,
    matricWeight: 0,
    interWeight: 40,
    testWeight: 60,
    testName: "LUMS LCAT / SAT",
    testMaxScore: 100,
    website: "https://lums.edu.pk",
    feesRange: "PKR 1,200,000 - 1,600,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 88, eligibility: "70% FSc / 3 A-Levels", seats: 100 },
      { name: "BS Business Administration", cutoffTypical: 85, eligibility: "70% FSc / FA", seats: 200 },
      { name: "BS Economics", cutoffTypical: 82, eligibility: "70% FSc / FA", seats: 100 },
    ],
  },
  {
    name: "University of Engineering & Technology Lahore",
    shortName: "UET Lahore",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 5,
    globalRank: 900,
    matricWeight: 17,
    interWeight: 50,
    testWeight: 33,
    testName: "ECAT",
    testMaxScore: 400,
    website: "https://uet.edu.pk",
    feesRange: "PKR 80,000 - 150,000/year",
    programs: [
      { name: "BS Electrical Engineering", cutoffTypical: 81, eligibility: "60% FSc Pre-Eng", seats: 200 },
      { name: "BS Mechanical Engineering", cutoffTypical: 79, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Civil Engineering", cutoffTypical: 77, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Computer Science", cutoffTypical: 83, eligibility: "60% FSc Pre-Eng/ICS", seats: 120 },
    ],
  },
  {
    name: "University of the Punjab",
    shortName: "PU Lahore",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 6,
    globalRank: 850,
    matricWeight: 0,
    interWeight: 70,
    testWeight: 30,
    testName: "PU Entry Test",
    testMaxScore: 100,
    website: "https://pu.edu.pk",
    feesRange: "PKR 40,000 - 90,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 86, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Software Engineering", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Information Technology", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },
  {
    name: "FAST National University Lahore",
    shortName: "FAST Lahore",
    city: "Lahore",
    province: "Punjab",
    type: "private",
    nationalRank: 11,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "FAST NU Test",
    testMaxScore: 100,
    website: "https://nu.edu.pk",
    feesRange: "PKR 350,000 - 450,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng/ICS", seats: 200 },
      { name: "BS Software Engineering", cutoffTypical: 74, eligibility: "60% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Artificial Intelligence", cutoffTypical: 77, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },

  // --- SINDH ---
  {
    name: "NED University of Engineering and Technology",
    shortName: "NED Karachi",
    city: "Karachi",
    province: "Sindh",
    type: "public",
    nationalRank: 7,
    globalRank: null,
    matricWeight: 0,
    interWeight: 40,
    testWeight: 60,
    testName: "NED Entry Test",
    testMaxScore: 100,
    website: "https://neduet.edu.pk",
    feesRange: "PKR 90,000 - 160,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 80, eligibility: "60% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Electrical Engineering", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Mechanical Engineering", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng", seats: 150 },
      { name: "BS Civil Engineering", cutoffTypical: 74, eligibility: "60% FSc Pre-Eng", seats: 160 },
    ],
  },
  {
    name: "Institute of Business Administration Karachi",
    shortName: "IBA Karachi",
    city: "Karachi",
    province: "Sindh",
    type: "public",
    nationalRank: 8,
    globalRank: null,
    matricWeight: 0,
    interWeight: 40,
    testWeight: 60,
    testName: "IBA Entry Test / SAT",
    testMaxScore: 100,
    website: "https://iba.edu.pk",
    feesRange: "PKR 450,000 - 650,000/year",
    programs: [
      { name: "BS Business Administration", cutoffTypical: 82, eligibility: "65% FSc/FA", seats: 250 },
      { name: "BS Accounting & Finance", cutoffTypical: 80, eligibility: "65% FSc/FA", seats: 150 },
      { name: "BS Computer Science", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },
  {
    name: "Aga Khan University",
    shortName: "AKU Karachi",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 9,
    globalRank: 500,
    matricWeight: 0,
    interWeight: 30,
    testWeight: 70,
    testName: "AKU Admission Test",
    testMaxScore: 100,
    website: "https://aku.edu",
    feesRange: "PKR 1,500,000 - 2,000,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 90, eligibility: "70% FSc Pre-Medical", seats: 100 },
      { name: "BS Nursing", cutoffTypical: 75, eligibility: "50% FSc Pre-Med", seats: 80 },
    ],
  },
  {
    name: "Mehran University of Engineering and Technology",
    shortName: "Mehran UET",
    city: "Jamshoro",
    province: "Sindh",
    type: "public",
    nationalRank: 18,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MUET Pre-Admission Test",
    testMaxScore: 100,
    website: "https://muet.edu.pk",
    feesRange: "PKR 60,000 - 120,000/year",
    programs: [
      { name: "BS Civil Engineering", cutoffTypical: 72, eligibility: "60% FSc Pre-Eng", seats: 200 },
      { name: "BS Electrical Engineering", cutoffTypical: 70, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Software Engineering", cutoffTypical: 74, eligibility: "60% FSc Pre-Eng/ICS", seats: 120 },
    ],
  },

  // --- KHYBER PAKHTUNKHWA (KPK) ---
  {
    name: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    shortName: "GIKI",
    city: "Topi",
    province: "KPK",
    type: "private",
    nationalRank: 10,
    globalRank: null,
    matricWeight: 0,
    interWeight: 15,
    testWeight: 85,
    testName: "GIKI Entry Test",
    testMaxScore: 200,
    website: "https://giki.edu.pk",
    feesRange: "PKR 850,000 - 1,100,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Cyber Security", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 50 },
      { name: "BS Mechanical Engineering", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng", seats: 90 },
      { name: "BS Electrical Engineering", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng", seats: 90 },
    ],
  },
  {
    name: "University of Engineering and Technology Peshawar",
    shortName: "UET Peshawar",
    city: "Peshawar",
    province: "KPK",
    type: "public",
    nationalRank: 12,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "KPK ETEA ECAT",
    testMaxScore: 800,
    website: "https://uetpeshawar.edu.pk",
    feesRange: "PKR 70,000 - 140,000/year",
    programs: [
      { name: "BS Civil Engineering", cutoffTypical: 75, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Electrical Engineering", cutoffTypical: 73, eligibility: "60% FSc Pre-Eng", seats: 160 },
      { name: "BS Computer Science", cutoffTypical: 77, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },
  {
    name: "Institute of Management Sciences Peshawar",
    shortName: "IMSciences",
    city: "Peshawar",
    province: "KPK",
    type: "public",
    nationalRank: 22,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "IMSciences Entry Test",
    testMaxScore: 100,
    website: "https://imsciences.edu.pk",
    feesRange: "PKR 120,000 - 200,000/year",
    programs: [
      { name: "BS Business Administration", cutoffTypical: 68, eligibility: "50% FSc/FA", seats: 120 },
      { name: "BS Computer Science", cutoffTypical: 72, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },

  // --- BALOCHISTAN ---
  {
    name: "Balochistan University of Information Technology, Engineering and Management Sciences",
    shortName: "BUITEMS",
    city: "Quetta",
    province: "Balochistan",
    type: "public",
    nationalRank: 16,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "BUITEMS NTS Test",
    testMaxScore: 100,
    website: "https://buitms.edu.pk",
    feesRange: "PKR 60,000 - 120,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "50% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 63, eligibility: "50% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Petroleum Engineering", cutoffTypical: 67, eligibility: "60% FSc Pre-Eng", seats: 60 },
      { name: "BS Civil Engineering", cutoffTypical: 66, eligibility: "60% FSc Pre-Eng", seats: 100 },
    ],
  },
  {
    name: "University of Balochistan",
    shortName: "UOB Quetta",
    city: "Quetta",
    province: "Balochistan",
    type: "public",
    nationalRank: 25,
    globalRank: null,
    matricWeight: 10,
    interWeight: 50,
    testWeight: 40,
    testName: "UOB Entry Test",
    testMaxScore: 100,
    website: "https://uob.edu.pk",
    feesRange: "PKR 30,000 - 70,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 60, eligibility: "45% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Geology", cutoffTypical: 58, eligibility: "45% FSc Science", seats: 80 },
    ],
  },

  // --- AZAD JAMMU & KASHMIR (AJK) ---
  {
    name: "Mirpur University of Science and Technology",
    shortName: "MUST AJK",
    city: "Mirpur",
    province: "AJK",
    type: "public",
    nationalRank: 28,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MUST Entry Test",
    testMaxScore: 100,
    website: "https://must.edu.pk",
    feesRange: "PKR 50,000 - 110,000/year",
    programs: [
      { name: "BS Electrical Engineering", cutoffTypical: 68, eligibility: "60% FSc Pre-Eng", seats: 100 },
      { name: "BS Computer Science", cutoffTypical: 70, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },

  // --- GILGIT-BALTISTAN ---
  {
    name: "Karakoram International University",
    shortName: "KIU Gilgit",
    city: "Gilgit",
    province: "Gilgit-Baltistan",
    type: "public",
    nationalRank: 30,
    globalRank: null,
    matricWeight: 20,
    interWeight: 50,
    testWeight: 30,
    testName: "KIU Test",
    testMaxScore: 100,
    website: "https://kiu.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 62, eligibility: "50% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Earth Sciences", cutoffTypical: 58, eligibility: "45% FSc Science", seats: 60 },
    ],
  },
  
  // --- NEW MAJOR MAIN CAMPUSES ADDED ---
  {
    name: "Quaid-e-Azam University",
    shortName: "QAU",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 1, // General
    globalRank: 400,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "USAT (Pass/Fail)",
    testMaxScore: 100,
    website: "https://qau.edu.pk",
    feesRange: "PKR 50,000 - 90,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 88, eligibility: "50% FSc", seats: 100 },
      { name: "BS Physics", cutoffTypical: 85, eligibility: "50% FSc", seats: 60 },
    ],
  },
  {
    name: "King Edward Medical University",
    shortName: "KEMU",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 1, // Medical
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MDCAT",
    testMaxScore: 200,
    website: "https://kemu.edu.pk",
    feesRange: "PKR 30,000 - 60,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 93, eligibility: "65% FSc Pre-Medical", seats: 300 },
      { name: "BDS", cutoffTypical: 91, eligibility: "65% FSc Pre-Medical", seats: 100 },
    ],
  },
  {
    name: "Dow University of Health Sciences",
    shortName: "DUHS",
    city: "Karachi",
    province: "Sindh",
    type: "public",
    nationalRank: 2, // Medical
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MDCAT",
    testMaxScore: 200,
    website: "https://duhs.edu.pk",
    feesRange: "PKR 50,000 - 150,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 89, eligibility: "65% FSc Pre-Medical", seats: 350 },
      { name: "BDS", cutoffTypical: 87, eligibility: "65% FSc Pre-Medical", seats: 150 },
    ],
  },
  {
    name: "University of Agriculture Faisalabad",
    shortName: "UAF",
    city: "Faisalabad",
    province: "Punjab",
    type: "public",
    nationalRank: 4,
    globalRank: 800,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "UAF Entry Test",
    testMaxScore: 100,
    website: "https://uaf.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "BS Agriculture", cutoffTypical: 75, eligibility: "50% FSc", seats: 400 },
      { name: "BS Computer Science", cutoffTypical: 80, eligibility: "50% FSc", seats: 100 },
    ],
  },
  {
    name: "University of Karachi",
    shortName: "UoK",
    city: "Karachi",
    province: "Sindh",
    type: "public",
    nationalRank: 10,
    globalRank: 1000,
    matricWeight: 0,
    interWeight: 100,
    testWeight: 0,
    testName: "KU Entry Test (Pass/Fail for some)",
    testMaxScore: 100,
    website: "https://uok.edu.pk",
    feesRange: "PKR 30,000 - 70,000/year",
    programs: [
      { name: "BS Software Engineering", cutoffTypical: 82, eligibility: "50% FSc", seats: 120 },
      { name: "Pharm-D", cutoffTypical: 85, eligibility: "60% FSc", seats: 200 },
    ],
  },
  {
    name: "National University of Modern Languages",
    shortName: "NUML",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 15,
    globalRank: null,
    matricWeight: 5,
    interWeight: 10,
    testWeight: 85, // 75% Entry Test + 10% Interview combined
    testName: "NUML Entry Test",
    testMaxScore: 100,
    website: "https://numl.edu.pk",
    feesRange: "PKR 60,000 - 100,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 72, eligibility: "50% FSc", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 70, eligibility: "50% FSc", seats: 120 },
      { name: "BS English", cutoffTypical: 65, eligibility: "45% FA/FSc", seats: 200 },
    ],
  },
  
  // --- BATCH 2: NEXT 10 MAJOR UNIVERSITIES ---
  {
    name: "Bahauddin Zakariya University",
    shortName: "BZU",
    city: "Multan",
    province: "Punjab",
    type: "public",
    nationalRank: 12,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "BZU Entry Test (Pass/Fail)",
    testMaxScore: 100,
    website: "https://bzu.edu.pk",
    feesRange: "PKR 40,000 - 70,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 78, eligibility: "50% FSc", seats: 120 },
      { name: "BS Information Technology", cutoffTypical: 75, eligibility: "50% FSc", seats: 100 },
    ],
  },
  {
    name: "Government College University",
    shortName: "GCU",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 14,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "GCU Test",
    testMaxScore: 100,
    website: "https://gcu.edu.pk",
    feesRange: "PKR 50,000 - 80,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 84, eligibility: "50% FSc", seats: 80 },
      { name: "BS Psychology", cutoffTypical: 80, eligibility: "50% FSc/FA", seats: 60 },
    ],
  },
  {
    name: "Shaheed Zulfikar Ali Bhutto Institute of Science and Technology",
    shortName: "SZABIST",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 20,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "SZABIST Entry Test",
    testMaxScore: 100,
    website: "https://szabist.edu.pk",
    feesRange: "PKR 250,000 - 350,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "50% FSc", seats: 150 },
      { name: "BBA", cutoffTypical: 68, eligibility: "50% FA/FSc", seats: 200 },
    ],
  },
  {
    name: "National Defence University",
    shortName: "NDU",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 25,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "NDU Entry Test",
    testMaxScore: 100,
    website: "https://ndu.edu.pk",
    feesRange: "PKR 80,000 - 120,000/year",
    programs: [
      { name: "BS International Relations", cutoffTypical: 70, eligibility: "50% FA/FSc", seats: 100 },
      { name: "BS Strategic Studies", cutoffTypical: 68, eligibility: "50% FA/FSc", seats: 80 },
    ],
  },
  {
    name: "Institute of Space Technology",
    shortName: "IST",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 30,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "IST Entry Test",
    testMaxScore: 100,
    website: "https://ist.edu.pk",
    feesRange: "PKR 120,000 - 180,000/year",
    programs: [
      { name: "BS Aerospace Engineering", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng", seats: 80 },
      { name: "BS Computer Science", cutoffTypical: 75, eligibility: "60% FSc Pre-Eng", seats: 100 },
    ],
  },
  {
    name: "University of Central Punjab",
    shortName: "UCP",
    city: "Lahore",
    province: "Punjab",
    type: "private",
    nationalRank: 35,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "UCP Admission Test (Pass/Fail)",
    testMaxScore: 100,
    website: "https://ucp.edu.pk",
    feesRange: "PKR 250,000 - 350,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "50% FSc", seats: 300 },
      { name: "BBA", cutoffTypical: 60, eligibility: "45% FA/FSc", seats: 400 },
    ],
  },
  {
    name: "University of Management and Technology",
    shortName: "UMT",
    city: "Lahore",
    province: "Punjab",
    type: "private",
    nationalRank: 36,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "UMT Admission Test",
    testMaxScore: 100,
    website: "https://umt.edu.pk",
    feesRange: "PKR 250,000 - 380,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 62, eligibility: "50% FSc", seats: 350 },
      { name: "BS Software Engineering", cutoffTypical: 60, eligibility: "50% FSc", seats: 250 },
    ],
  },
  {
    name: "Riphah International University",
    shortName: "Riphah",
    city: "Islamabad",
    province: "Federal",
    type: "private",
    nationalRank: 40,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "Riphah Entry Test",
    testMaxScore: 100,
    website: "https://riphah.edu.pk",
    feesRange: "PKR 200,000 - 450,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 68, eligibility: "50% FSc", seats: 200 },
      { name: "DPT (Physical Therapy)", cutoffTypical: 72, eligibility: "60% FSc Pre-Medical", seats: 100 },
    ],
  },
  {
    name: "Iqra University",
    shortName: "Iqra",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 42,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "Iqra Admission Test",
    testMaxScore: 100,
    website: "https://iqra.edu.pk",
    feesRange: "PKR 200,000 - 300,000/year",
    programs: [
      { name: "BBA", cutoffTypical: 55, eligibility: "45% FA/FSc", seats: 300 },
      { name: "BS Computer Science", cutoffTypical: 60, eligibility: "50% FSc", seats: 250 },
    ],
  },
  {
    name: "Capital University of Science & Technology",
    shortName: "CUST",
    city: "Islamabad",
    province: "Federal",
    type: "private",
    nationalRank: 45,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "CUST Entry Test",
    testMaxScore: 100,
    website: "https://cust.edu.pk",
    feesRange: "PKR 220,000 - 320,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "50% FSc", seats: 200 },
      { name: "BS Software Engineering", cutoffTypical: 63, eligibility: "50% FSc", seats: 150 },
    ],
  },
  
  // --- BATCH 3 & 4: NEXT 20 UNIVERSITIES (SINDH, PUNJAB, KPK, BALOCHISTAN) ---
  {
    name: "University of Sindh",
    shortName: "UoS Jamshoro",
    city: "Jamshoro",
    province: "Sindh",
    type: "public",
    nationalRank: 15,
    globalRank: null,
    matricWeight: 10,
    interWeight: 30,
    testWeight: 60,
    testName: "UoS Entry Test",
    testMaxScore: 100,
    website: "https://usindh.edu.pk",
    feesRange: "PKR 30,000 - 60,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "50% FSc", seats: 150 },
      { name: "BBA", cutoffTypical: 60, eligibility: "45% FA/FSc", seats: 200 }
    ]
  },
  {
    name: "Sukkur IBA University",
    shortName: "Sukkur IBA",
    city: "Sukkur",
    province: "Sindh",
    type: "public",
    nationalRank: 18,
    globalRank: null,
    matricWeight: 0,
    interWeight: 40,
    testWeight: 60,
    testName: "STS Entry Test",
    testMaxScore: 100,
    website: "https://iba-suk.edu.pk",
    feesRange: "PKR 80,000 - 150,000/year",
    programs: [
      { name: "BBA", cutoffTypical: 65, eligibility: "50% FSc", seats: 120 },
      { name: "BS Computer Science", cutoffTypical: 68, eligibility: "50% FSc", seats: 100 }
    ]
  },
  {
    name: "Quaid-e-Awam University of Engineering, Science and Technology",
    shortName: "QUEST",
    city: "Nawabshah",
    province: "Sindh",
    type: "public",
    nationalRank: 35,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "QUEST Entry Test",
    testMaxScore: 100,
    website: "https://quest.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "BS Civil Engineering", cutoffTypical: 68, eligibility: "60% FSc Pre-Eng", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 70, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 }
    ]
  },
  {
    name: "Shah Abdul Latif University",
    shortName: "SALU",
    city: "Khairpur",
    province: "Sindh",
    type: "public",
    nationalRank: 40,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "No Entry Test (Mostly)",
    testMaxScore: 100,
    website: "https://salu.edu.pk",
    feesRange: "PKR 30,000 - 60,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 60, eligibility: "45% FSc", seats: 80 }
    ]
  },
  {
    name: "University of Sargodha",
    shortName: "UOS",
    city: "Sargodha",
    province: "Punjab",
    type: "public",
    nationalRank: 22,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "Merit Based (No Test)",
    testMaxScore: 100,
    website: "https://su.edu.pk",
    feesRange: "PKR 40,000 - 70,000/year",
    programs: [
      { name: "BS Information Technology", cutoffTypical: 75, eligibility: "50% FSc", seats: 120 },
      { name: "BS English", cutoffTypical: 70, eligibility: "50% FA/FSc", seats: 100 }
    ]
  },
  {
    name: "Islamia University of Bahawalpur",
    shortName: "IUB",
    city: "Bahawalpur",
    province: "Punjab",
    type: "public",
    nationalRank: 20,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "IUB Admission Test (Pass/Fail)",
    testMaxScore: 100,
    website: "https://iub.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 72, eligibility: "50% FSc", seats: 200 },
      { name: "Pharm-D", cutoffTypical: 80, eligibility: "60% FSc Pre-Medical", seats: 150 }
    ]
  },
  {
    name: "University of Gujrat",
    shortName: "UOG",
    city: "Gujrat",
    province: "Punjab",
    type: "public",
    nationalRank: 30,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://uog.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "BS Software Engineering", cutoffTypical: 78, eligibility: "50% FSc", seats: 100 }
    ]
  },
  {
    name: "Fatima Jinnah Women University",
    shortName: "FJWU",
    city: "Rawalpindi",
    province: "Punjab",
    type: "public",
    nationalRank: 32,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "NTS NAT (for some)",
    testMaxScore: 100,
    website: "https://fjwu.edu.pk",
    feesRange: "PKR 45,000 - 85,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 70, eligibility: "50% FSc", seats: 80 }
    ]
  },
  {
    name: "International Islamic University Islamabad",
    shortName: "IIUI",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 16,
    globalRank: null,
    matricWeight: 20,
    interWeight: 40,
    testWeight: 40,
    testName: "IIUI Entry Test",
    testMaxScore: 100,
    website: "https://iiu.edu.pk",
    feesRange: "PKR 50,000 - 100,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 74, eligibility: "50% FSc", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 72, eligibility: "50% FSc", seats: 100 }
    ]
  },
  {
    name: "Foundation University",
    shortName: "FUI",
    city: "Islamabad",
    province: "Federal",
    type: "private",
    nationalRank: 40,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "FUI Entry Test",
    testMaxScore: 100,
    website: "https://fui.edu.pk",
    feesRange: "PKR 150,000 - 250,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "50% FSc", seats: 120 }
    ]
  },
  {
    name: "Shifa Tameer-e-Millat University",
    shortName: "STMU",
    city: "Islamabad",
    province: "Federal",
    type: "private",
    nationalRank: 42,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MDCAT / STMU Test",
    testMaxScore: 100,
    website: "https://stmu.edu.pk",
    feesRange: "PKR 300,000 - 600,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 62, eligibility: "50% FSc", seats: 80 },
      { name: "MBBS", cutoffTypical: 85, eligibility: "65% FSc Pre-Medical", seats: 100 }
    ]
  },
  {
    name: "Gomal University",
    shortName: "GU",
    city: "D.I. Khan",
    province: "KPK",
    type: "public",
    nationalRank: 38,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://gu.edu.pk",
    feesRange: "PKR 30,000 - 60,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 60, eligibility: "45% FSc", seats: 100 }
    ]
  },
  {
    name: "Abdul Wali Khan University",
    shortName: "AWKUM",
    city: "Mardan",
    province: "KPK",
    type: "public",
    nationalRank: 25,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://awkum.edu.pk",
    feesRange: "PKR 35,000 - 65,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "45% FSc", seats: 120 }
    ]
  },
  {
    name: "Kohat University of Science and Technology",
    shortName: "KUST",
    city: "Kohat",
    province: "KPK",
    type: "public",
    nationalRank: 45,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://kust.edu.pk",
    feesRange: "PKR 30,000 - 60,000/year",
    programs: [
      { name: "BS Software Engineering", cutoffTypical: 64, eligibility: "45% FSc", seats: 80 }
    ]
  },
  {
    name: "University of Malakand",
    shortName: "UoM",
    city: "Chakdara",
    province: "KPK",
    type: "public",
    nationalRank: 48,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://uom.edu.pk",
    feesRange: "PKR 35,000 - 65,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 62, eligibility: "45% FSc", seats: 100 }
    ]
  },
  {
    name: "Hazara University",
    shortName: "HU",
    city: "Mansehra",
    province: "KPK",
    type: "public",
    nationalRank: 50,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://hu.edu.pk",
    feesRange: "PKR 35,000 - 60,000/year",
    programs: [
      { name: "BS Information Technology", cutoffTypical: 60, eligibility: "45% FSc", seats: 100 }
    ]
  },
  {
    name: "Lasbela University of Agriculture, Water and Marine Sciences",
    shortName: "LUAWMS",
    city: "Uthal",
    province: "Balochistan",
    type: "public",
    nationalRank: 55,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://luawms.edu.pk",
    feesRange: "PKR 25,000 - 50,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 55, eligibility: "45% FSc", seats: 60 }
    ]
  },
  {
    name: "Iqra National University",
    shortName: "INU",
    city: "Peshawar",
    province: "KPK",
    type: "private",
    nationalRank: 58,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "INU Test",
    testMaxScore: 100,
    website: "https://inu.edu.pk",
    feesRange: "PKR 150,000 - 200,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 58, eligibility: "45% FSc", seats: 100 }
    ]
  },
  {
    name: "CECOS University of IT and Emerging Sciences",
    shortName: "CECOS",
    city: "Peshawar",
    province: "KPK",
    type: "private",
    nationalRank: 60,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "CECOS Entry Test",
    testMaxScore: 100,
    website: "https://cecos.edu.pk",
    feesRange: "PKR 160,000 - 220,000/year",
    programs: [
      { name: "BS Civil Engineering", cutoffTypical: 60, eligibility: "60% FSc Pre-Eng", seats: 80 },
      { name: "BS Computer Science", cutoffTypical: 55, eligibility: "50% FSc", seats: 120 }
    ]
  },
  {
    name: "National Textile University",
    shortName: "NTU",
    city: "Faisalabad",
    province: "Punjab",
    type: "public",
    nationalRank: 33,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "NTS NAT",
    testMaxScore: 100,
    website: "https://ntu.edu.pk",
    feesRange: "PKR 50,000 - 90,000/year",
    programs: [
      { name: "BS Textile Engineering", cutoffTypical: 65, eligibility: "60% FSc Pre-Eng", seats: 100 },
      { name: "BS Computer Science", cutoffTypical: 72, eligibility: "50% FSc", seats: 80 }
    ],
  },
  
  // --- BATCH 5: FINAL 14 UNIVERSITIES (REACHING 70 TARGET) ---
  {
    name: "University of Engineering and Technology Taxila",
    shortName: "UET Taxila",
    city: "Taxila",
    province: "Punjab",
    type: "public",
    nationalRank: 17,
    globalRank: null,
    matricWeight: 17,
    interWeight: 50,
    testWeight: 33,
    testName: "ECAT",
    testMaxScore: 400,
    website: "https://uettaxila.edu.pk",
    feesRange: "PKR 60,000 - 120,000/year",
    programs: [
      { name: "BS Civil Engineering", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng", seats: 120 },
      { name: "BS Software Engineering", cutoffTypical: 80, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 }
    ]
  },
  {
    name: "Muhammad Nawaz Sharif UET",
    shortName: "MNS UET",
    city: "Multan",
    province: "Punjab",
    type: "public",
    nationalRank: 42,
    globalRank: null,
    matricWeight: 17,
    interWeight: 50,
    testWeight: 33,
    testName: "ECAT",
    testMaxScore: 400,
    website: "https://mnsuet.edu.pk",
    feesRange: "PKR 50,000 - 90,000/year",
    programs: [
      { name: "BS Chemical Engineering", cutoffTypical: 68, eligibility: "60% FSc Pre-Eng", seats: 80 }
    ]
  },
  {
    name: "NFC Institute of Engineering and Fertilizer Research",
    shortName: "NFC IEFR",
    city: "Faisalabad",
    province: "Punjab",
    type: "public",
    nationalRank: 48,
    globalRank: null,
    matricWeight: 17,
    interWeight: 50,
    testWeight: 33,
    testName: "ECAT",
    testMaxScore: 400,
    website: "https://iefr.edu.pk",
    feesRange: "PKR 60,000 - 100,000/year",
    programs: [
      { name: "BS Electrical Engineering", cutoffTypical: 65, eligibility: "60% FSc Pre-Eng", seats: 100 }
    ]
  },
  {
    name: "Khawaja Fareed University of Engineering and Information Technology",
    shortName: "KFUEIT",
    city: "Rahim Yar Khan",
    province: "Punjab",
    type: "public",
    nationalRank: 34,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://kfueit.edu.pk",
    feesRange: "PKR 45,000 - 85,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 70, eligibility: "50% FSc", seats: 150 }
    ]
  },
  {
    name: "Information Technology University",
    shortName: "ITU",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 24,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "ITU Admission Test",
    testMaxScore: 100,
    website: "https://itu.edu.pk",
    feesRange: "PKR 80,000 - 150,000/year",
    programs: [
      { name: "BS Artificial Intelligence", cutoffTypical: 82, eligibility: "60% FSc", seats: 80 },
      { name: "BS Computer Science", cutoffTypical: 84, eligibility: "60% FSc", seats: 120 }
    ]
  },
  {
    name: "Kinnaird College for Women",
    shortName: "Kinnaird",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 26,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based (Aptitude for some)",
    testMaxScore: 100,
    website: "https://kinnaird.edu.pk",
    feesRange: "PKR 70,000 - 130,000/year",
    programs: [
      { name: "BS Psychology", cutoffTypical: 82, eligibility: "60% FA/FSc", seats: 80 }
    ]
  },
  {
    name: "Lahore College for Women University",
    shortName: "LCWU",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 28,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://lcwu.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "BS English", cutoffTypical: 75, eligibility: "60% FA/FSc", seats: 100 }
    ]
  },
  {
    name: "National College of Arts",
    shortName: "NCA",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 31,
    globalRank: null,
    matricWeight: 10,
    interWeight: 20,
    testWeight: 70,
    testName: "NCA Aptitude Test",
    testMaxScore: 100,
    website: "https://nca.edu.pk",
    feesRange: "PKR 100,000 - 180,000/year",
    programs: [
      { name: "B.Arch (Architecture)", cutoffTypical: 70, eligibility: "60% FA/FSc", seats: 50 },
      { name: "Fine Arts", cutoffTypical: 65, eligibility: "60% FA/FSc", seats: 60 }
    ]
  },
  {
    name: "University of Education",
    shortName: "UE",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 38,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://ue.edu.pk",
    feesRange: "PKR 35,000 - 65,000/year",
    programs: [
      { name: "BS Information Technology", cutoffTypical: 70, eligibility: "50% FSc", seats: 120 }
    ]
  },
  {
    name: "University of Sahiwal",
    shortName: "UoSahiwal",
    city: "Sahiwal",
    province: "Punjab",
    type: "public",
    nationalRank: 65,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://uosahiwal.edu.pk",
    feesRange: "PKR 30,000 - 55,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 68, eligibility: "50% FSc", seats: 80 }
    ]
  },
  {
    name: "Jinnah Sindh Medical University",
    shortName: "JSMU",
    city: "Karachi",
    province: "Sindh",
    type: "public",
    nationalRank: 12, // Medical
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MDCAT",
    testMaxScore: 200,
    website: "https://jsmu.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 88, eligibility: "65% FSc Pre-Med", seats: 200 }
    ]
  },
  {
    name: "Liaquat University of Medical & Health Sciences",
    shortName: "LUMHS",
    city: "Jamshoro",
    province: "Sindh",
    type: "public",
    nationalRank: 14, // Medical
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MDCAT",
    testMaxScore: 200,
    website: "https://lumhs.edu.pk",
    feesRange: "PKR 45,000 - 85,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 86, eligibility: "65% FSc Pre-Med", seats: 250 }
    ]
  },
  {
    name: "Khyber Medical University",
    shortName: "KMU",
    city: "Peshawar",
    province: "KPK",
    type: "public",
    nationalRank: 16, // Medical
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MDCAT / ETEA",
    testMaxScore: 200,
    website: "https://kmu.edu.pk",
    feesRange: "PKR 50,000 - 100,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 87, eligibility: "65% FSc Pre-Med", seats: 200 }
    ]
  },
  {
    name: "Bolan University of Medical and Health Sciences",
    shortName: "BUMHS",
    city: "Quetta",
    province: "Balochistan",
    type: "public",
    nationalRank: 25, // Medical
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MDCAT",
    testMaxScore: 200,
    website: "https://bumhs.edu.pk",
    feesRange: "PKR 35,000 - 65,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 80, eligibility: "65% FSc Pre-Med", seats: 150 }
    ]
  },
  {
    name: "National University of Modern Languages",
    shortName: "NUML",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 15,
    globalRank: null,
    matricWeight: 5,
    interWeight: 10,
    testWeight: 85,
    testName: "NUML Entry Test",
    testMaxScore: 100,
    website: "https://numl.edu.pk",
    feesRange: "PKR 60,000 - 100,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 72, eligibility: "50% FSc", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 70, eligibility: "50% FSc", seats: 120 },
      { name: "BS English", cutoffTypical: 65, eligibility: "45% FA/FSc", seats: 200 }
    ]
  },
  
  // --- BATCH 6: HEC CAMPUS LIST REMAINING UNIVERSITIES ---
  {
    name: "Federal Urdu University of Arts, Sciences & Technology",
    shortName: "FUUAST",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 35,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://fuuast.edu.pk",
    feesRange: "PKR 40,000 - 70,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 68, eligibility: "50% FSc", seats: 150 }
    ]
  },
  {
    name: "Virtual University of Pakistan",
    shortName: "VU",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 40,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based (Open)",
    testMaxScore: 100,
    website: "https://vu.edu.pk",
    feesRange: "PKR 25,000 - 45,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 50, eligibility: "45% FSc", seats: 1000 }
    ]
  },
  {
    name: "University of Veterinary & Animal Sciences",
    shortName: "UVAS",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 18,
    globalRank: null,
    matricWeight: 30,
    interWeight: 70,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://uvas.edu.pk",
    feesRange: "PKR 50,000 - 90,000/year",
    programs: [
      { name: "DVM", cutoffTypical: 85, eligibility: "60% FSc Pre-Med", seats: 120 }
    ]
  },
  {
    name: "Hamdard University",
    shortName: "Hamdard",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 42,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "Hamdard Entry Test",
    testMaxScore: 100,
    website: "https://hamdard.edu.pk",
    feesRange: "PKR 200,000 - 400,000/year",
    programs: [
      { name: "Pharm-D", cutoffTypical: 65, eligibility: "60% FSc Pre-Med", seats: 150 },
      { name: "BS Computer Science", cutoffTypical: 60, eligibility: "50% FSc", seats: 100 }
    ]
  },
  {
    name: "Preston University",
    shortName: "Preston",
    city: "Kohat",
    province: "KPK",
    type: "private",
    nationalRank: 55,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://preston.edu.pk",
    feesRange: "PKR 100,000 - 150,000/year",
    programs: [
      { name: "BBA", cutoffTypical: 50, eligibility: "45% FA/FSc", seats: 150 }
    ]
  },
  {
    name: "Sarhad University of Science & Information Technology",
    shortName: "SUIT",
    city: "Peshawar",
    province: "KPK",
    type: "private",
    nationalRank: 48,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "SUIT Test",
    testMaxScore: 100,
    website: "https://suit.edu.pk",
    feesRange: "PKR 120,000 - 180,000/year",
    programs: [
      { name: "BS Software Engineering", cutoffTypical: 58, eligibility: "50% FSc", seats: 120 }
    ]
  },
  {
    name: "Ziauddin University",
    shortName: "Ziauddin",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 30, // Medical mostly
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "Ziauddin Entry Test",
    testMaxScore: 100,
    website: "https://zu.edu.pk",
    feesRange: "PKR 350,000 - 600,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 78, eligibility: "65% FSc Pre-Med", seats: 100 }
    ]
  },
  {
    name: "Hajvery University",
    shortName: "HU",
    city: "Lahore",
    province: "Punjab",
    type: "private",
    nationalRank: 50,
    globalRank: null,
    matricWeight: 20,
    interWeight: 80,
    testWeight: 0,
    testName: "Merit Based",
    testMaxScore: 100,
    website: "https://hup.edu.pk",
    feesRange: "PKR 150,000 - 250,000/year",
    programs: [
      { name: "BBA", cutoffTypical: 55, eligibility: "45% FA/FSc", seats: 150 }
    ]
  },
  {
    name: "Greenwich University",
    shortName: "Greenwich",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 60,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "Aptitude Test",
    testMaxScore: 100,
    website: "https://greenwich.edu.pk",
    feesRange: "PKR 250,000 - 400,000/year",
    programs: [
      { name: "BS Mass Communication", cutoffTypical: 60, eligibility: "45% FA/FSc", seats: 80 }
    ]
  },
  {
    name: "Ilma University",
    shortName: "Ilma",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 65,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "Ilma Admission Test",
    testMaxScore: 100,
    website: "https://ilmauniversity.edu.pk",
    feesRange: "PKR 150,000 - 200,000/year",
    programs: [
      { name: "BBA", cutoffTypical: 50, eligibility: "45% FA/FSc", seats: 150 }
    ]
  }
];
