export interface UniversitySeed {
  name: string;
  shortName: string;
  city: string;
  province: string; // "Punjab" | "Sindh" | "KPK" | "Balochistan" | "Federal" | "AJK" | "Gilgit-Baltistan"
  type: "public" | "private";
  nationalRank: number | null;
  globalRank: number | null;
  matricWeight: number;
  interWeight: number;
  testWeight: number;
  testName: string;
  testMaxScore: number;
  website: string;
  feesRange: string;
  programs: ProgramSeed[];
}

export interface ProgramSeed {
  name: string;
  cutoffTypical: number;
  eligibility: string;
  seats: number | null;
}

export const UNIVERSITY_SEED_DATA: UniversitySeed[] = [
  // --- FEDERAL / ISLAMABAD ---
  {
    name: "National University of Sciences & Technology",
    shortName: "NUST",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 1,
    globalRank: 650,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "NET",
    testMaxScore: 200,
    website: "https://nust.edu.pk",
    feesRange: "PKR 200,000 - 350,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 85, eligibility: "60% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 83, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Artificial Intelligence", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Data Science", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 60 },
      { name: "BS Electrical Engineering", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng", seats: 120 },
      { name: "BS Mechanical Engineering", cutoffTypical: 80, eligibility: "60% FSc Pre-Eng", seats: 100 },
      { name: "BS Civil Engineering", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng", seats: 100 },
      { name: "BS Business Administration", cutoffTypical: 78, eligibility: "60% FSc/FA", seats: 80 },
    ],
  },
  {
    name: "COMSATS University Islamabad",
    shortName: "COMSATS",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 3,
    globalRank: 800,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "NTS NAT",
    testMaxScore: 100,
    website: "https://comsats.edu.pk",
    feesRange: "PKR 120,000 - 220,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 78, eligibility: "50% FSc Pre-Eng/ICS", seats: 250 },
      { name: "BS Software Engineering", cutoffTypical: 76, eligibility: "50% FSc Pre-Eng/ICS", seats: 200 },
      { name: "BS Cyber Security", cutoffTypical: 75, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Electrical Engineering", cutoffTypical: 70, eligibility: "60% FSc Pre-Eng", seats: 150 },
      { name: "BS Business Administration", cutoffTypical: 65, eligibility: "50% FSc/FA", seats: 120 },
    ],
  },
  {
    name: "Pakistan Institute of Engineering and Applied Sciences",
    shortName: "PIEAS",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 4,
    globalRank: 400,
    matricWeight: 15,
    interWeight: 25,
    testWeight: 60,
    testName: "PIEAS Admission Test",
    testMaxScore: 100,
    website: "https://pieas.edu.pk",
    feesRange: "PKR 100,000 - 180,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 60 },
      { name: "BS Electrical Engineering", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng", seats: 60 },
      { name: "BS Mechanical Engineering", cutoffTypical: 83, eligibility: "60% FSc Pre-Eng", seats: 60 },
      { name: "BS Chemical Engineering", cutoffTypical: 80, eligibility: "60% FSc Pre-Eng", seats: 50 },
    ],
  },
  {
    name: "Air University",
    shortName: "Air Uni",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 15,
    globalRank: null,
    matricWeight: 15,
    interWeight: 35,
    testWeight: 50,
    testName: "Air University Entry Test",
    testMaxScore: 100,
    website: "https://au.edu.pk",
    feesRange: "PKR 150,000 - 250,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 74, eligibility: "50% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Cyber Security", cutoffTypical: 73, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Software Engineering", cutoffTypical: 72, eligibility: "50% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Avionics Engineering", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng", seats: 60 },
    ],
  },
  {
    name: "Bahria University",
    shortName: "Bahria",
    city: "Islamabad",
    province: "Federal",
    type: "public",
    nationalRank: 20,
    globalRank: null,
    matricWeight: 20,
    interWeight: 30,
    testWeight: 50,
    testName: "CBT Bahria Test",
    testMaxScore: 100,
    website: "https://bahria.edu.pk",
    feesRange: "PKR 180,000 - 280,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 68, eligibility: "50% FSc Pre-Eng/ICS", seats: 180 },
      { name: "BS Information Technology", cutoffTypical: 65, eligibility: "50% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Business Administration", cutoffTypical: 62, eligibility: "50% FSc/FA", seats: 150 },
    ],
  },

  // --- PUNJAB ---
  {
    name: "Lahore University of Management Sciences",
    shortName: "LUMS",
    city: "Lahore",
    province: "Punjab",
    type: "private",
    nationalRank: 2,
    globalRank: 700,
    matricWeight: 0,
    interWeight: 40,
    testWeight: 60,
    testName: "LUMS LCAT / SAT",
    testMaxScore: 100,
    website: "https://lums.edu.pk",
    feesRange: "PKR 1,200,000 - 1,600,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 88, eligibility: "70% FSc / 3 A-Levels", seats: 100 },
      { name: "BS Business Administration", cutoffTypical: 85, eligibility: "70% FSc / FA", seats: 200 },
      { name: "BS Economics", cutoffTypical: 82, eligibility: "70% FSc / FA", seats: 100 },
    ],
  },
  {
    name: "University of Engineering & Technology Lahore",
    shortName: "UET Lahore",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 5,
    globalRank: 900,
    matricWeight: 17,
    interWeight: 50,
    testWeight: 33,
    testName: "ECAT",
    testMaxScore: 400,
    website: "https://uet.edu.pk",
    feesRange: "PKR 80,000 - 150,000/year",
    programs: [
      { name: "BS Electrical Engineering", cutoffTypical: 81, eligibility: "60% FSc Pre-Eng", seats: 200 },
      { name: "BS Mechanical Engineering", cutoffTypical: 79, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Civil Engineering", cutoffTypical: 77, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Computer Science", cutoffTypical: 83, eligibility: "60% FSc Pre-Eng/ICS", seats: 120 },
    ],
  },
  {
    name: "University of the Punjab",
    shortName: "PU Lahore",
    city: "Lahore",
    province: "Punjab",
    type: "public",
    nationalRank: 6,
    globalRank: 850,
    matricWeight: 0,
    interWeight: 70,
    testWeight: 30,
    testName: "PU Entry Test",
    testMaxScore: 100,
    website: "https://pu.edu.pk",
    feesRange: "PKR 40,000 - 90,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 86, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Software Engineering", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Information Technology", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },
  {
    name: "FAST National University Lahore",
    shortName: "FAST Lahore",
    city: "Lahore",
    province: "Punjab",
    type: "private",
    nationalRank: 11,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "FAST NU Test",
    testMaxScore: 100,
    website: "https://nu.edu.pk",
    feesRange: "PKR 350,000 - 450,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng/ICS", seats: 200 },
      { name: "BS Software Engineering", cutoffTypical: 74, eligibility: "60% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Artificial Intelligence", cutoffTypical: 77, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },

  // --- SINDH ---
  {
    name: "NED University of Engineering and Technology",
    shortName: "NED Karachi",
    city: "Karachi",
    province: "Sindh",
    type: "public",
    nationalRank: 7,
    globalRank: null,
    matricWeight: 0,
    interWeight: 50,
    testWeight: 50,
    testName: "NED Entry Test",
    testMaxScore: 100,
    website: "https://neduet.edu.pk",
    feesRange: "PKR 90,000 - 160,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 80, eligibility: "60% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Electrical Engineering", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Mechanical Engineering", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng", seats: 150 },
      { name: "BS Civil Engineering", cutoffTypical: 74, eligibility: "60% FSc Pre-Eng", seats: 160 },
    ],
  },
  {
    name: "Institute of Business Administration Karachi",
    shortName: "IBA Karachi",
    city: "Karachi",
    province: "Sindh",
    type: "public",
    nationalRank: 8,
    globalRank: null,
    matricWeight: 0,
    interWeight: 40,
    testWeight: 60,
    testName: "IBA Entry Test / SAT",
    testMaxScore: 100,
    website: "https://iba.edu.pk",
    feesRange: "PKR 450,000 - 650,000/year",
    programs: [
      { name: "BS Business Administration", cutoffTypical: 82, eligibility: "65% FSc/FA", seats: 250 },
      { name: "BS Accounting & Finance", cutoffTypical: 80, eligibility: "65% FSc/FA", seats: 150 },
      { name: "BS Computer Science", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },
  {
    name: "Aga Khan University",
    shortName: "AKU Karachi",
    city: "Karachi",
    province: "Sindh",
    type: "private",
    nationalRank: 9,
    globalRank: 500,
    matricWeight: 0,
    interWeight: 30,
    testWeight: 70,
    testName: "AKU Admission Test",
    testMaxScore: 100,
    website: "https://aku.edu",
    feesRange: "PKR 1,500,000 - 2,000,000/year",
    programs: [
      { name: "MBBS", cutoffTypical: 90, eligibility: "70% FSc Pre-Medical", seats: 100 },
      { name: "BS Nursing", cutoffTypical: 75, eligibility: "50% FSc Pre-Med", seats: 80 },
    ],
  },
  {
    name: "Mehran University of Engineering and Technology",
    shortName: "Mehran UET",
    city: "Jamshoro",
    province: "Sindh",
    type: "public",
    nationalRank: 18,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MUET Pre-Admission Test",
    testMaxScore: 100,
    website: "https://muet.edu.pk",
    feesRange: "PKR 60,000 - 120,000/year",
    programs: [
      { name: "BS Civil Engineering", cutoffTypical: 72, eligibility: "60% FSc Pre-Eng", seats: 200 },
      { name: "BS Electrical Engineering", cutoffTypical: 70, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Software Engineering", cutoffTypical: 74, eligibility: "60% FSc Pre-Eng/ICS", seats: 120 },
    ],
  },

  // --- KHYBER PAKHTUNKHWA (KPK) ---
  {
    name: "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology",
    shortName: "GIKI",
    city: "Topi",
    province: "KPK",
    type: "private",
    nationalRank: 10,
    globalRank: null,
    matricWeight: 0,
    interWeight: 15,
    testWeight: 85,
    testName: "GIKI Entry Test",
    testMaxScore: 200,
    website: "https://giki.edu.pk",
    feesRange: "PKR 850,000 - 1,100,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 84, eligibility: "60% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Cyber Security", cutoffTypical: 82, eligibility: "60% FSc Pre-Eng/ICS", seats: 50 },
      { name: "BS Mechanical Engineering", cutoffTypical: 78, eligibility: "60% FSc Pre-Eng", seats: 90 },
      { name: "BS Electrical Engineering", cutoffTypical: 76, eligibility: "60% FSc Pre-Eng", seats: 90 },
    ],
  },
  {
    name: "University of Engineering and Technology Peshawar",
    shortName: "UET Peshawar",
    city: "Peshawar",
    province: "KPK",
    type: "public",
    nationalRank: 12,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "KPK ETEA ECAT",
    testMaxScore: 800,
    website: "https://uetpeshawar.edu.pk",
    feesRange: "PKR 70,000 - 140,000/year",
    programs: [
      { name: "BS Civil Engineering", cutoffTypical: 75, eligibility: "60% FSc Pre-Eng", seats: 180 },
      { name: "BS Electrical Engineering", cutoffTypical: 73, eligibility: "60% FSc Pre-Eng", seats: 160 },
      { name: "BS Computer Science", cutoffTypical: 77, eligibility: "60% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },
  {
    name: "Institute of Management Sciences Peshawar",
    shortName: "IMSciences",
    city: "Peshawar",
    province: "KPK",
    type: "public",
    nationalRank: 22,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "IMSciences Entry Test",
    testMaxScore: 100,
    website: "https://imsciences.edu.pk",
    feesRange: "PKR 120,000 - 200,000/year",
    programs: [
      { name: "BS Business Administration", cutoffTypical: 68, eligibility: "50% FSc/FA", seats: 120 },
      { name: "BS Computer Science", cutoffTypical: 72, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },

  // --- BALOCHISTAN ---
  {
    name: "Balochistan University of Information Technology, Engineering and Management Sciences",
    shortName: "BUITEMS",
    city: "Quetta",
    province: "Balochistan",
    type: "public",
    nationalRank: 16,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "BUITEMS NTS Test",
    testMaxScore: 100,
    website: "https://buitms.edu.pk",
    feesRange: "PKR 60,000 - 120,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 65, eligibility: "50% FSc Pre-Eng/ICS", seats: 150 },
      { name: "BS Software Engineering", cutoffTypical: 63, eligibility: "50% FSc Pre-Eng/ICS", seats: 120 },
      { name: "BS Petroleum Engineering", cutoffTypical: 67, eligibility: "60% FSc Pre-Eng", seats: 60 },
      { name: "BS Civil Engineering", cutoffTypical: 66, eligibility: "60% FSc Pre-Eng", seats: 100 },
    ],
  },
  {
    name: "University of Balochistan",
    shortName: "UOB Quetta",
    city: "Quetta",
    province: "Balochistan",
    type: "public",
    nationalRank: 25,
    globalRank: null,
    matricWeight: 10,
    interWeight: 50,
    testWeight: 40,
    testName: "UOB Entry Test",
    testMaxScore: 100,
    website: "https://uob.edu.pk",
    feesRange: "PKR 30,000 - 70,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 60, eligibility: "45% FSc Pre-Eng/ICS", seats: 100 },
      { name: "BS Geology", cutoffTypical: 58, eligibility: "45% FSc Science", seats: 80 },
    ],
  },

  // --- AZAD JAMMU & KASHMIR (AJK) ---
  {
    name: "Mirpur University of Science and Technology",
    shortName: "MUST AJK",
    city: "Mirpur",
    province: "AJK",
    type: "public",
    nationalRank: 28,
    globalRank: null,
    matricWeight: 10,
    interWeight: 40,
    testWeight: 50,
    testName: "MUST Entry Test",
    testMaxScore: 100,
    website: "https://must.edu.pk",
    feesRange: "PKR 50,000 - 110,000/year",
    programs: [
      { name: "BS Electrical Engineering", cutoffTypical: 68, eligibility: "60% FSc Pre-Eng", seats: 100 },
      { name: "BS Computer Science", cutoffTypical: 70, eligibility: "50% FSc Pre-Eng/ICS", seats: 100 },
    ],
  },

  // --- GILGIT-BALTISTAN ---
  {
    name: "Karakoram International University",
    shortName: "KIU Gilgit",
    city: "Gilgit",
    province: "Gilgit-Baltistan",
    type: "public",
    nationalRank: 30,
    globalRank: null,
    matricWeight: 20,
    interWeight: 50,
    testWeight: 30,
    testName: "KIU Test",
    testMaxScore: 100,
    website: "https://kiu.edu.pk",
    feesRange: "PKR 40,000 - 80,000/year",
    programs: [
      { name: "BS Computer Science", cutoffTypical: 62, eligibility: "50% FSc Pre-Eng/ICS", seats: 80 },
      { name: "BS Earth Sciences", cutoffTypical: 58, eligibility: "45% FSc Science", seats: 60 },
    ],
  },
];
